fix price restriction formatting
QuickShop-Community/QuickShop-Hikari pull request #1765
Opened 2024-09-09 08:51 UTC by TauCubed

Only display both min and max price messages if there is a min and max price set. Otherwise, just display one or the other.
Don't decimal format price restriction messages as you may lose required granularity.

2024-09-11 08:47 UTC, Ghost-chu requested changes

2024-09-11 08:47 UTC, Ghost-chu commented on quickshop-bukkit/src/main/java/com/ghostchu/quickshop/util/ShopUtil.java
> +        plugin.text().of(user, "price-too-cheap", currency + checkResult.getMin()).send();
This is bad, use economy formatter. Different economic plug-ins have different requirements for formatting currencies, and directly adding them up will break the currency formatting

2024-09-11 08:47 UTC, Ghost-chu commented on quickshop-bukkit/src/main/java/com/ghostchu/quickshop/util/ShopUtil.java
> +        plugin.text().of(user, "price-too-high", currency + checkResult.getMax()).send();
This is bad, use economy formatter. Different economic plug-ins have different requirements for formatting currencies, and directly adding them up will break the currency formatting

2024-09-17 00:13 UTC, creatorfromhell commented
@Ghost-chu How do the changes look for you?

2026-06-10 12:56 UTC, creatorfromhell commented
Corrected the conflicts and readjusted for merging in https://github.com/QuickShop-Community/QuickShop-Hikari/pull/2362

2026-06-10 12:56 UTC, closed without merging

2026-06-10 12:56 UTC, creatorfromhell commented
Thank you for your contribution.